### PR TITLE
Test deprecate-router-events codemod

### PR DESCRIPTION
**Pull request by rajasegar**
https://github.com/ember-cli/ember-cli-update-codemods-manifest/issues/21

https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/24

### CODE REVIEW

**Comment by rajasegar** [comment]
@kellyselden Any idea how I can re-trigger the build for this PR?

**Comment by kellyselden** [comment]
Looks like there's a failure with newlines with the codemod. https://travis-ci.org/ember-cli/ember-cli-update/jobs/593930566#L4994

**Comment by rajasegar** [comment]
@kellyselden I think it's due to the quote difference single vs double , not because of newline character , I have fixed the same in the codemod, so need to trigger the build again and check. That's why I have asked.
https://github.com/ember-codemods/ember-3x-codemods/pull/8

**Comment by kellyselden** [comment]
Can you rebase master? I made some improvements to the test times.

**Comment by kellyselden** [comment]
it's still a newline issue.

**Comment by rajasegar** [comment]
@kellyselden Yes, from  the beginning there was the new line issue, but apart from that we also had other issues within the transform. Finally, I figured out all of them. Thanks for reviewing.

**Pull request merged**
