### PR TITLE
try deprecate-merge codemod

### PR DESCRIPTION
**Pull request by rajasegar**
test https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/23

### CODE REVIEW

**Comment by rajasegar** [comment]
retest this please

**Comment by rajasegar** [comment]
retest this

**Comment by rajasegar** [comment]
@kellyselden No problem, but I don't know why the test cases are failing even if I change everything to double quotes, still the actual and expected values are different.

**Comment by kellyselden** [comment]
Everything should be single quotes.

**Pull request merged**
