### PR TITLE
add ember-test-helpers-codemod

### PR DESCRIPTION
**Pull request by kellyselden**
cc @simonihmig

### CODE REVIEW

**Comment by simonihmig** [comment]
Great! 👍

Not sure what broke the test though, as it seems to be working in node 4!? 🤔

**Comment by kellyselden** [comment]
It was #282

**Comment by simonihmig** [comment]
Ah, yeah, makes sense!

**Comment by kellyselden** [comment]
@simonihmig I'm getting 

```
(node:6088) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at getAllFiles.then.then.pendingWorkers (/home/travis/.npm/_npx/5737/lib/node_modules/ember-test-helpers-codemod/node_modules/jscodeshift/src/Runner.js:259:17)
    at <anonymous>
```

in my logs. Does that mean anything to you? https://travis-ci.org/kellyselden/ember-cli-update/jobs/359459462#L4695

**Comment by simonihmig** [comment]
No, not really. Also saw that in the first failed build...

I would *guess* this could happen when jscodeshift could not parse some file, at least I remember seeing similar weird errors when some file contained invalid JS. But really just guessing...

Is this running on these fixtures? https://github.com/kellyselden/ember-cli-update/tree/master/test/fixtures/codemod/my-app

Would obviously be nice to have this reproducible outside of Travis ;)

**Comment by kellyselden** [comment]
@simonihmig I just ran it locally on "test/fixtures/merge/my-app" and got it. Using node 8.

**Comment by simonihmig** [comment]
Ok, could also reproduce. It's weird, it seems this pops up whenever you run `jscodeshift` on a folder with no matching files (`*.js`). And it's unrelated to my codemod, the same happened when testing this with `ember-modules-codemod`:

```bash
$ jscodeshift -t ~/Projects/ember-modules-codemod/transform.js -d tests/integration/
No files selected, nothing to do. 
(node:1979) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
(node:1979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As soon as there is at least one file to transform (like when running on whole `tests/` folder, which contains at least `test-helper.js`), it works again. Similar report: https://github.com/reactjs/react-codemod/issues/87

🙄

**Comment by simonihmig** [comment]
All attempts to provide a workaround did not succeed. Filed https://github.com/facebook/jscodeshift/issues/250

**Comment by kellyselden** [comment]
This work now goes on in https://github.com/ember-cli/ember-cli-update-codemods-manifest

**Pull request closed without merging**
