### PR TITLE
add createCustomDiff option

### LINKED ISSUE #113: conflict with `my-app` or `my-addon`
The blueprint output repo uses app and addon names prefixed with "my". Any line that updates will merge conflict with your app name. We could fix this by doing some post-processing on the output repos to inject your app name in the files, so that there will no longer be a conflict.

### LINKED ISSUE #125: yarn projects don't get clean diffs
the output repos only record the standard blueprint, not the yarn variant or any others. Projects using a variant will get weird conflicts.

I don't know if there is a sane way to fix this.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #125

Use your own versions of apps instead of the output repo's. The intent is to mix with your own .ember-cli file to get your own catered diffs. This is much slower (and more error-prone if it is a really old version) than the normal way to update.

```
ember-cli-update --custom-remote
```

@rwjblue @rwwagner90 @Turbo87 does this solve your yarn issues?

### CODE REVIEW

**Comment by rwwagner90** [comment]
@kellyselden I don't think this solves the yarn issue. From the description it sounds like we would need to maintain another repo that has all the yarn output to compare against. Can we not follow the `if yarn` checks ember-cli already provides for `ember init` in some way and compare to the same diffs?

**Comment by kellyselden** [comment]
@rwwagner90 Did you try it? --custom-remote is a bool, not a string. It tells it to use your system settings to generate a diff instead of an output repo.

**Comment by rwwagner90** [comment]
@kellyselden oh, I misunderstood then. Could we just have this happen automatically when yarn is detected perhaps?

**Comment by kellyselden** [comment]
Possibly, but I'd like to have it opt-in to start. This method is extremely slow, and so maybe some yarn users would prefer the instantaneous update method with the downside of incorrect conflicts sometimes?

**Comment by rwwagner90** [comment]
Is it not possible to generate repos for yarn and npm somehow, and just switch which ones we compare to or if not can we not use repos at all and do whatever `ember init` does? I'm not very knowledgable about the whole process, but if there is no good out of the box solution, we should log a warning saying not to use this if you use yarn, and to use `ember init`. There is heavy use of yarn in Ember projects, so it would be awesome if we had a way both npm and yarn were first class citizens.

**Comment by kellyselden** [comment]
I would say the default ember install is always the first class citizen, and everything else is second. It's not just npm and yarn, there's also module unification, no-welcome-screen, etc, then you would have to cross-product all those to get all the possibilities. The out-of-the-box solution to these is to use --custom-remote. I don't think that's that bad.

**Comment by kellyselden** [comment]
I guess we will always disagree then. Tracking yarn, MU, typescript, and all the other non-default project types and their cross-product combinations would be tough. Making an exception for yarn and not the others is not something I personally feel like doing.

**Comment by rwwagner90** [comment]
@kellyselden are there `if` statements in the default ember-cli blueprints for all those other things? I'm only advocating `yarn` support because it's explicitly supported by the `if` statements in the blueprints.

**Comment by kellyselden** [comment]
There's an if for the welcome-screen and a whole set of blueprints for module unification.

**Comment by rwwagner90** [comment]
So why don't we prune some of the official support for these things? If Ember wants to recommend and enforce `npm`, we should do that everywhere, I would think.

**Comment by Turbo87** [comment]
> If Ember wants to recommend and enforce npm, we should do that everywhere, I would think.

I don't think that's what Kelly was saying...

**Comment by rwwagner90** [comment]
In my opinion, if ember-cli supports `yarn` out of the box, and `ember-cli-update` is now the recommended and supported way of updating, and we're recommending it over `ember init` it should work for `yarn`. 

I know I started using yarn as it was recommended more and more throughout the Ember community, so I think there will be others that expect support out of the box, and will be similarly surprised when it doesn't work.

I think there would be value in either fully supporting both, and generating repos for the yarn output or whatever we need to do to support that, or moving toward only supporting npm in general. The biggest thing I love about Ember is that it makes things easy and enforces standards, so I am open to doing whatever is most supported.

**Comment by kellyselden** [comment]
I've confirmed this works for the yarn problem with a system .ember-cli file. Any final opinions on the name of this bool before merge? @rwjblue @Turbo87

**Comment by kellyselden** [comment]
What about
* `--use-custom-diff`
* `--use-personal-diff`
* `--create-custom-diff`
* `--create-personal-diff`
* `--generate-custom-diff`
* `--generate-personal-diff`

?

**Comment by rwjblue** [comment]
TBH, all of yours sound good to me, though I'd _slightly_ lean towards `-create-custom-diff`...

**Pull request merged**
