### PR TITLE
document run codemod after updating

### PR DESCRIPTION
**Pull request by maxwondercorn**
#339

### CODE REVIEW

**Comment by kellyselden** [comment]
these messages are synced up across files. I would prefer it be in a description body outside of this table if possible.

**Comment by maxwondercorn** [comment]
I went back and forth whether to put it in the table or outside. Would it make sense to put it into the Hints section or more separate?  Seems link hints is dedicated to merging.  

Simple PR so I don't want to make it more difficult than it should be!

BTW, I've used this to update several projects and I love how it removes all the pain points.

**Comment by kellyselden** [comment]
I would put it in the usage section. There isn't a paragraph about codemods yet I believe so you may have to describe what it's doing before the hint will make sense.

**Comment by kellyselden** [comment]
Thanks!

**Pull request merged**
